spring:
  application:
    name: pipeline-sentinel
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

pipeline-sentinel:
  cors:
    allowed-origins: ${PIPELINE_SENTINEL_CORS_ALLOWED_ORIGINS:http://localhost:3000}
